1 PRINT
2 PRINT
3 PRINT
4 PRINT
5 PRINT
6 PRINT
7 PRINT
8 PRINT
9 PRINT
10 PRINT "                     **************************"
20 PRINT "                     *                        *"
30 PRINT "                     *       MATH WORLD!      *"
40 PRINT "                     *                        *"
50 PRINT "                     *     BY: BEN FRANCK     *"
60 PRINT "                     **************************"
61 PRINT
62 PRINT
63 PRINT
64 PRINT
65 PRINT
70 PRINT "     YOU ARE AT SCHOOL DURING A BORING MATH CLASS. YOU ARE STUDYING ON ADDING"
80 PRINT " LARGE NUMBERS. YOU SLOWLY DRIFT TO SLEEP AND DREAM ABOUT A STRANGE WORLD OF..."
90 PRINT "                               MATH!"
100 PRINT "                      (TYPE GO TO CONTINUE)"
INPUT A$
110 PRINT

