
SCREEN 9
FOR I% = 1 TO 10
COLOR I%
NEXT I%
PRINT "                          SIM ORBIT"
PRINT "                       BY: BEN FRANCK"
PRINT
PRINT "         PRESS ANY KEY TO SEE THE MOON ORBIT THE EARTH "
INPUT S$
1 SCREEN 10
BEEP
PRINT
PRINT
PRINT
PRINT
PRINT "                              EEEEE"
PRINT "                              EEEEE"
PRINT "                              EEEEE"
PRINT
PRINT "                                  "
PRINT "                               MMM"
BEEP
SCREEN 9
PRINT
PRINT
PRINT
PRINT
PRINT "                              EEEEE"
PRINT "                              EEEEE     MMM"
PRINT "                              EEEEE"
PRINT
PRINT
PRINT
BEEP
SCREEN 10
PRINT
PRINT "                               MMM"
PRINT
PRINT "                      "
PRINT "                              EEEEE"
PRINT "                              EEEEE"
PRINT "                              EEEEE"
PRINT
PRINT
PRINT
BEEP
SCREEN 9
PRINT
PRINT
PRINT
PRINT "                            "
PRINT "                              EEEEE"
PRINT "                       MMM    EEEEE"
PRINT "                              EEEEE"
PRINT
PRINT
PRINT
BEEP
PRINT "THAT IS THE END. PRESS V TO VEIW IT AGAIN OR ANY KEY TO EXIT"
INPUT A$
IF A$ = "V" THEN 1
END

